.TH GWMPULSE 1 2019\-11\-24 Linux "User Manuals"
.hy
.SH NAME
.PP
\f[B]gwmpulse\f[R] - Pulse window border.
Uses \f[B]BORDER\f[R] from \f[B]\[ti]/.config/gwm/config\f[R]
.SH SYNOPSIS
.IP
.nf
\f[B]
gwmpulse &
gwmpulse --help|-h
\f[R]
.fi
.SH EXAMPLES
.PP
Pulsing border
.PP
[[/images/pulse.gif|pulse]]
.PP
Rainbow border
.PP
[[/images/rainbow.gif|rainbow]]
