.TH GWMSBAR 1 2019\-11\-24 Linux "User Manuals"
.hy
.SH NAME
.PP
\f[B]gwmsbar\f[R] - Create sidebar of windows, stacked like cards, with
a single fully visible window at the top
.SH SYNOPSIS
.IP
.nf
\f[B]
gwmsbar [--stack|-a|--clean|-c|--focus|-f|--major|-M|--minor|-m]
        \fI<WID|>\fP
gwmsbar --cycle|-n|--focus-cycle|-F|--restack|-r|--reset|-R
gwmsbar --help|-h
\f[R]
.fi
